package com.beam.app.protocol.transfer

import java.security.SecureRandom
import java.util.UUID

object BeamIds {
    private val random = SecureRandom()

    /**
     * 16-byte UUID, generated by the sender,
     * unique across all transfers.
     */
    fun newTransferId(): String = UUID.randomUUID().toString()

    /**
     * 8 random bytes, lowercase hex,
     * generated by the sender,
     * session-scoped.
     * One file offered to N peers reuses the same
     * `fileId` with N distinct `transferId`s.
     */
    fun newFileId(): String {
        val bytes = ByteArray(FILE_ID_BYTES)
        random.nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }

    private const val FILE_ID_BYTES = 8
}
